# Generated by Django 4.0.5 on 2022-07-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('medio', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('medio', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuderia', models.CharField(default='', max_length=10)),
                ('nacionalidad', models.CharField(default='', max_length=15)),
                ('patrocinador', models.CharField(default='', max_length=15)),
                ('proov_motor', models.CharField(default='', max_length=15)),
                ('mod_motor', models.CharField(default='', max_length=15)),
                ('proov_chasis', models.CharField(default='', max_length=15)),
                ('mod_chasis', models.CharField(default='', max_length=15)),
                ('gp_anfitrion', models.CharField(default=None, max_length=15)),
                ('pil_ppal', models.CharField(default='', max_length=15)),
                ('pil_sec', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.team')),
                ('nombre', models.CharField(default='', max_length=15)),
                ('apellido', models.CharField(default='', max_length=15)),
                ('puesto', models.CharField(default='', max_length=15)),
            ],
            bases=('WebF1.team',),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.empleado')),
                ('universidad', models.CharField(default='', max_length=20)),
                ('titulo', models.CharField(default='', max_length=20)),
                ('especialidad', models.CharField(default='', max_length=15)),
            ],
            bases=('WebF1.empleado',),
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.empleado')),
                ('universidad', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=15)),
            ],
            bases=('WebF1.empleado',),
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.empleado')),
                ('circuito', models.CharField(max_length=15)),
            ],
            bases=('WebF1.empleado',),
        ),
    ]
