# Generated by Django 4.0.5 on 2022-07-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=15)),
                ('apellido', models.CharField(default='', max_length=15)),
                ('nacionalidad', models.CharField(default='', max_length=25)),
                ('experiencia', models.IntegerField(default=0)),
                ('edad', models.IntegerField(default=0)),
                ('escuderia', models.CharField(default='', max_length=25)),
                ('puesto', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('medio', models.CharField(default='', max_length=20)),
                ('matricula', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuderia', models.CharField(default='', max_length=10)),
                ('nacionalidad', models.CharField(default='', max_length=15)),
                ('patrocinador', models.CharField(default='', max_length=15)),
                ('proov_motor', models.CharField(default='', max_length=15)),
                ('mod_motor', models.CharField(default='', max_length=15)),
                ('proov_chasis', models.CharField(default='', max_length=15)),
                ('mod_chasis', models.CharField(default='', max_length=15)),
                ('gp_anfitrion', models.CharField(default='', max_length=15)),
                ('pil_ppal', models.CharField(default='', max_length=15)),
                ('pil_sec', models.CharField(default='', max_length=15)),
                ('cant_emp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.empleado')),
                ('universidad', models.CharField(default='', max_length=20)),
                ('titulo', models.CharField(default='', max_length=20)),
                ('especialidad', models.CharField(default='', max_length=15)),
                ('ocupacion', models.CharField(default='', max_length=25)),
            ],
            bases=('WebF1.empleado',),
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebF1.empleado')),
                ('campeonatos_disputados', models.IntegerField(default=0)),
                ('campeonatos_ganados', models.IntegerField(default=0)),
                ('circuito_favorito', models.CharField(max_length=15)),
                ('poles', models.IntegerField(default=0)),
                ('carreras_disputadas', models.IntegerField(default=0)),
                ('carreras_ganadas', models.IntegerField(default=0)),
            ],
            bases=('WebF1.empleado',),
        ),
    ]
