# Generated by Django 4.0.5 on 2022-07-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebF1', '0002_administrativo_email_administrativo_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='fan',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
    ]
