# Generated by Django 4.0.5 on 2022-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebF1', '0002_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='creador',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
    ]
