# Generated by Django 4.0.5 on 2022-07-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebF1', '0003_fan_email_fan_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='medio',
        ),
        migrations.AddField(
            model_name='fan',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='periodista',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='gp_anfitrion',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='pil_sec',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Administrativo',
        ),
    ]
